title: Snowflake ARCTIC
subtitle: Advanced Research Computing Technology and Innovation Centre

titles_from_headings:
  enabled: true
  strip_title: true

remote_theme: jekyll/minima
minima:
  skin: solarized
  
google_site_verification: fvYz1B8yNW7ty9JFQlUtitr1iLDZOkcJKmXBDw61DJM
bing_site_verification: 6EC6EF9289FCA6EB99E61F2A3C5064FE
